### ISSUE TITLE
New team member onboarding checklist: neilmb

### ISSUE THREAD

**Issue by neilmb** [18F/tock#1134]
- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x] Grant access to gsa-18f-tock org on Snyk.

(per https://github.com/18F/tock/blob/main/docs/onboarding.md)

**Comment by tbaxter-18f** [comment]
Neil, on the GH repo, I think you have all access needed, but if not, please let me or Joe know.

**Comment by neilmb** [comment]
I am wanting access to the Cloud.gov roles for staging at least. Is there someone who can help that happen?

**Comment by Jkrzy** [comment]
Added remaining permissions, welcome aboard @neilmb!
