### ISSUE TITLE
New team member onboarding checklist: @tadhg-ohiggins 

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1190]
Welcome @tadhg-ohiggins!

We'll run through the checklist and get you access to :all-the-things:

- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Send invitation to #tock-dev in Slack.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

(per https://github.com/18F/tock/blob/main/docs/onboarding.md)

**Comment by Jkrzy** [comment]
@tadhg-ohiggins, you've got access to :all-the-things:

Please tackle these at your leisure and then close this issue.
- [ ]  Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ]  Reviewed the Tock deployment process.
