### ISSUE TITLE
New team member onboarding checklist: @kfoley-18F 

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1268]
:happy-tock: Welcome @kfoley-18F ! :happy-tock:

I will run through the checklist and get you access to :all-the-things:

- [x] Generate a Tock API authorization token in the admin for the new developer.
- [ ]  Grant access to New Relic. <can't access NewRelic at the moment>
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Send invitation to #tock-dev in Slack.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

(per https://github.com/18F/tock/blob/main/docs/onboarding.md)

**Comment by kfoley-18F** [comment]
New Tock dev and Chief Tock Officer reporting for duty!
Log reviews accomplished, release made, still working on complete codebase familiarity. 

Closing this out as done.
