### ISSUE TITLE
New team member onboarding checklist: @kewlguy781

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1305]
Let's run through the checklist and get you set up with all the things!
:happy-tock: Welcome @kewlguy781 ! :happy-tock:

- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Send invitation to #tock-dev in Slack.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

Before getting too far, check out:

- [ ]  Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ]  Reviewed the Tock deployment process.

**Comment by kewlguy781** [comment]
overdue to be closed :)
