### ISSUE TITLE
New team member onboarding checklist: @caleywoods

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1349]
Let's run through the checklist and get you set up with all the things!
:happy-tock: Welcome @matthinz! :happy-tock:

- [ ]  Generate a Tock API authorization token in the admin for the new developer.
- [ ]  Grant access to New Relic.
- [ ]  Grant access to the GitHub repository.
- [ ]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [ ]  Send invitation to #tock-dev in Slack.
- [ ]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [ ]  Grant access to gsa-18f-tock org on Snyk.

You will need to be sure you have:
- [ ]  Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ]  Reviewed the Tock deployment process.
