### ISSUE TITLE
New team member onboarding checklist: @lauraGgit

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1387]
Let's run through the checklist and get you set up with all the things!
:happy-tock: Welcome @lauraGgit! :happy-tock:

- [x]  Generate a Tock API authorization token in the admin for the new developer.
- [ ]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Send invitation to #tock-dev in Slack.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

You will need to be sure you have:

- [ ]  Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ]  Reviewed the Tock deployment process.

**Comment by kfoley-18F** [comment]
Will need to request New Relic access from #admins-newrelic when I get access to NR... 😆

**Comment by cantsin** [comment]
Closing due to age.
