### ISSUE TITLE
[Epic] Update https://tock.18f.gov/utilization tables to account for weekly billing

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1500]
As a person monitoring 18F staff utilization
I want to view utilization calculations that accommodates both hourly billing and weekly allocation
so that I have an accurate picture of how the target hours of staff are being used.

## Sub-issues

**Discovery**
- [x] [Understanding the impact to the billing process](https://github.com/18F/tock/issues/1588)

**Reinforce current tests to prep for development**
- [x] [Add `timecard.utilization` current value to tests](https://github.com/18F/tock/issues/1589)
- [x] [Add tests for current utilization views with combination of weekly and hourly billing](https://github.com/18F/tock/issues/1590)

**Develop!**
- [x] [Update the `timecard.utilization` field value's calculation to include weekly billing](https://github.com/18F/tock/issues/1591)
- [x] [Alter the utils to use the `timecard.utilization` field](https://github.com/18F/tock/issues/1592) (relies on #1591) (https://github.com/18F/tock/pull/1625)
- [x] Double check all documentation about utilization is updated (https://github.com/18F/tock/pull/1619)

## Original issue

https://tock.18f.gov/utilization is set up to roll up hours by chapter/department. It doesn't handle weekly billing, but it may need revisiting on how to show allocation + hours over a whole year. 
Let's revisit how this data is displayed to capture both weekly and hourly billed work.

**Comment by neilmb** [comment]
Need to decide whether to convert allocation percentages into "hours" to get a Utilization rate for each person, or keep them separate so you would have two utilizations?

**Comment by neilmb** [comment]
This page is `GroupUtilizationView` in `tock/utilization/views.py` and the hours data comes from `unit_billing_context()` in `tock/utilization/unit.py`.

**Comment by carjug** [comment]
Possibly convert all of the numbers in the chart to an allocation (%) and have it roll up to an average % allocation.
Where this gets tricky is to convert hourly folks into % allocations....
And also allocation rate (%) vs non-billable or OOO time (hours)

**Comment by mgwalker** [comment]
It sounds like this needs design and engineering work?

**Comment by jduss4** [comment]
I chatted with Kelsey a bit about the requirements for this ticket and did a little [rough information gathering in a document.](https://docs.google.com/document/d/1EeUHQO86HX1dN29POiEeOeGapN9jbTf6ZaSKDLPGMyQ/edit) 🔒 

I'm going to spend a little time looking at the code and figuring out if it's possible to make some tightly scoped changes for this issue. If it's something that will require large-ish changes or touch multiple parts of the code base, then Kelsey recommends that we put this issue down for now.

**Comment by jduss4** [comment]
This is my last day on the team for a bit so I need to drop this issue, but I've documented conversations with Kelsey, thoughts about the code, next steps, and screenshots of the current behavior in [this document](https://docs.google.com/document/d/1EeUHQO86HX1dN29POiEeOeGapN9jbTf6ZaSKDLPGMyQ/edit#).

I believe the next steps are:

1. Talk to Matt Jadud to understand how the billing scripts work and what code we should be particularly careful about messing with, as its use case is not tested within the Tock repo
1. Look into distinguishing between billable and non-billable projects, as weekly allocation can be either, but utilization should be only billable hours
1. Come up with a very clear formula for utilization (probably basically there, but lacking the billability aspect)
1. You may then want to spin off some separate issues for ensuring there are tests in place for the current behavior of weekly billing, altering the logic for calculating utilization, testing that change, etc

**Comment by jduss4** [comment]
@alexbielen @MelissaBraxton Tagging for your awareness -- this work is inflight but can be picked up by other engineers on the DA team as desired!

**Comment by alexbielen** [comment]
Thanks @jduss4 and thanks for the fantastic write-up.

**Comment by alexbielen** [comment]
Removing @neilmb and @kfoley-18F as assignees.

**Comment by geekygirlsarah** [comment]
I've also been digging into this as well, and trying to fill in more blanks in [the document that Jess started](https://docs.google.com/document/d/1EeUHQO86HX1dN29POiEeOeGapN9jbTf6ZaSKDLPGMyQ/edit#). I'm brewing on what the algorithm to do this right might look like, but will have to roll off DA/TLC crew before I'm done. I'll document it!

**Comment by alexbielen** [comment]
This was broken down into an Epic with the following issues:

Discovery

 https://github.com/18F/tock/issues/1588
Reinforce current tests to prep for development

 https://github.com/18F/tock/issues/1589
 https://github.com/18F/tock/issues/1590
Develop!

 https://github.com/18F/tock/issues/1591
 https://github.com/18F/tock/issues/1592 (relies on https://github.com/18F/tock/issues/1591)
 Double check all documentation about utilization is updated

**Comment by alexbielen** [comment]
Note to self: Which swimlane do epics go in?
