### ISSUE TITLE
New team member onboarding checklist for @geekygirlsarah

### ISSUE THREAD

**Issue by cantsin** [18F/tock#1586]
Let's run through the checklist and get you set up with all the things!
:happy-tock: Welcome @geekygirlsarah  ! :happy-tock:

- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x] ~Grant access to New Relic.~ (skipping new relic for now as we aren't using it for anything other than auditing.)
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x] Grant access to gsa-18f-tock org on Snyk.

You will need to be sure you have:

- [ ] Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ] Reviewed the Tock deployment process.

**Comment by cantsin** [comment]
I've given you access, so please make sure you read the docs and then I think this issue is good to close 🎉
