### ISSUE TITLE
New team member onboarding checklist for @peterrowland

### ISSUE THREAD

**Issue by peterrowland** [18F/tock#1718]
## Team member checklist
Before you get started onboarding, your Tock developer partner needs to take care of a few things.
They will [create a new issue](https://github.com/18f/tock/issues/new) with the following
checklist, work through it with you.
- [x] Generate a Tock API authorization token in the admin for the new developer.
- [ ] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [ ] Grant access to SpaceDeveloper roles on Cloud.gov for `staging` and `prod` spaces within the  `gsa-18f-tock` org.
- [x] Send invitation to #tock-dev in Slack.
- [ ] Grant access to `GSA_TE_TockLibrary` and `GSA_TE_UtilitiesLibrary` scripts.
- [ ] Grant access to `gsa-18f-tock` org on Snyk.

## New developer checklist
You will need to be sure you have:
- [ ] Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ] Reviewed the [Tock deployment process](https://github.com/18f/tock/tree/main/docs/deployment-process.md).

**Comment by cantsin** [comment]
@peterrowland side note, you already have write access to the Tock repository by virtue of being a member of [18F TLC Crew](https://github.com/orgs/18F/teams/18f-tlc-crew)

**Comment by juliaklindpaintner** [comment]
@peterrowland has been staffed to a project so we are closing this issue for now.
