### ISSUE TITLE
New team member onboarding checklist for @beechnut

### ISSUE THREAD

**Issue by cantsin** [18F/tock#1772]
## Team member checklist
Before you get started onboarding, your Tock developer partner needs to take care of a few things.
They will [create a new issue](https://github.com/18f/tock/issues/new) with the following
checklist, work through it with you.
- [x] Generate a Tock API authorization token in the admin for the new developer.
- [ ] [James initiated / pending] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for `staging` and `prod` spaces within the  `gsa-18f-tock` org.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to `GSA_TE_TockLibrary` and `GSA_TE_UtilitiesLibrary` scripts.
- [x] Grant access to `gsa-18f-tock` org on Snyk.

## New developer checklist
You will need to be sure you have:
- [ ] Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [x] Reviewed the [Tock deployment process](https://github.com/18f/tock/tree/main/docs/deployment-process.md).

**Comment by bpdesigns** [comment]
@cantsin I think this is just waiting for your review/access

**Comment by cantsin** [comment]
@beechnut did we get an invite to NR? if not, i can try again today

**Comment by beechnut** [comment]
@cantsin No, I haven't received anything. Thanks for checking.

**Comment by cantsin** [comment]
I think we're good here -- we need to ask the relevant slack channel for access but closing as we might not actually need NR access anymore.
