### ISSUE TITLE
Get comms together for announcing new USWDS implementation

### ISSUE THREAD

**Issue by maya** [18F/tock#538]
The implementation of #523.

Things to note:

This is not the _final_ design as branding folk have helped with that, it's getting some foundations setup for us to build upon.

Working draft: https://docs.google.com/document/d/15h6QHyGTAVEpXFx03ksjhfS9z8HnnkoI-Cf_OvFUmMA/edit
## TODO
- [x] Finish draft https://docs.google.com/document/d/15h6QHyGTAVEpXFx03ksjhfS9z8HnnkoI-Cf_OvFUmMA/edit
- [x] Get writing lab/critique group to edit
- [x] Email it out to 18F team email
