### ISSUE TITLE
Onboarding Checklist for Amy Mok

### ISSUE THREAD

**Issue by amymok** [18F/tock#971]
- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for `staging` and `prod` spaces within the  `gsa-18f-tock` org.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to `GSA_TE_TockLibrary` and `GSA_TE_UtilitiesLibrary` scripts.
- [x] Grant access to `gsa-18f-tock` org on Snyk.

**Comment by tbaxter-18f** [comment]
@timothy-spencer I've done a bunch here too. What do you think of handling the remaining stuff at the same time as Mat Caughron's onboarding?

**Comment by timothy-spencer** [comment]
Can do...  Did you want all the remaining checklist items done, or did you just want me to intro them to the log audit stuff?

**Comment by tbaxter-18f** [comment]
Check off any boxes you can do without too much effort. If there are some that are more difficult, we'll figure those out. Thanks!

**Comment by timothy-spencer** [comment]
All the checklist items have been checked!  Let us know if more needs to be done!
